// General Settings
const CANVAS = {
    WIDTH : 600,
    HEIGHT: 1000,
    BACKGROUND_COLOR : 'white'
}

CANVAS.MARGINS_RATIO = {
    LEFT : 0.075,
    RIGHT : 0.075,
    TOP : 0.01,
    BOTTOM : 0
}

CANVAS.MARGINS = {
    LEFT : CANVAS.WIDTH * CANVAS.MARGINS_RATIO.LEFT,
    RIGHT : CANVAS.WIDTH * CANVAS.MARGINS_RATIO.RIGHT,
    TOP : CANVAS.HEIGHT * CANVAS.MARGINS_RATIO.TOP,
    BOTTOM : CANVAS.HEIGHT * CANVAS.MARGINS_RATIO.BOTTOM
}

CANVAS.MARGINS_POSITION = {
    LEFT: CANVAS.MARGINS.LEFT,
    RIGHT: CANVAS.WIDTH - CANVAS.MARGINS.RIGHT,
    TOP: CANVAS.MARGINS.TOP,
    BOTTOM: CANVAS.HEIGHT - CANVAS.MARGINS.BOTTOM
}

const BACKGROUND_COLOR = "white"
const DEBUG_COLOR = "magenta"

// Project Settings
const N_SQUARES_H = 12
const N_SQUARES_V = 22

const SQUARE_SIZE = (CANVAS.WIDTH - CANVAS.MARGINS.LEFT - CANVAS.MARGINS.RIGHT)/N_SQUARES_H

const MAX_ROTATION = 45
const MAX_TRANSLATION = SQUARE_SIZE * 0.75