const CANVAS = {
    WIDTH : 600,
    HEIGHT: 600,
    BACKGROUND_COLOR : 'white'
}

CANVAS.MARGINS_RATIO = {
    LEFT : 0.1,
    RIGHT : 0.1,
    TOP : 0.1,
    BOTTOM : 0.1
}

CANVAS.MARGINS = {
    LEFT : CANVAS.WIDTH * CANVAS.MARGINS_RATIO.LEFT,
    RIGHT : CANVAS.WIDTH * (1 - CANVAS.MARGINS_RATIO.RIGHT),
    TOP : CANVAS.HEIGHT * CANVAS.MARGINS_RATIO.TOP,
    BOTTOM : CANVAS.HEIGHT * (1 - CANVAS.MARGINS_RATIO.BOTTOM)
}

const BACKGROUND_COLOR = "white"
const DEBUG_COLOR = "magenta"